[package]
name = "primes-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
tokio = { version = "1", features = ["full"] }
log = "0.4.0"
env_logger = "0.9.0"
